feat: upgrade version
argos-ci/argos-javascript pull request #12
Opened 2022-07-26 08:39 UTC by jsfez

2022-07-26 08:40 UTC, jsfez commented
@gregberge Je ne connais pas la procédure pour publier les nouvelles versions de packages Gatsby sur NPM. Je ne pense pas non plus avoir les droits pour le faire. Je veux bien que tu t'en charge plz.

2022-07-29 09:15 UTC, gregberge requested changes
> We don't upgrade like that, we need a changelog. Setup https://github.com/gregberge/react-teleporter/blob/main/package.json#L33 first.

Sorry, this is a mono-repo that uses Lerna. So we have to release it using lerna. Just remove the upgrade of version please, I will take care of it.

2022-07-29 09:15 UTC, gregberge commented on packages/gatsby-plugin-argos/package.json
> +    "gatsby": "~4"
```suggestion
    "gatsby": "^4.0.0"
```

2022-07-29 09:15 UTC, gregberge commented on packages/gatsby-plugin-argos/package.json
> +    "argos-cli": "~0",
```suggestion
    "argos-cli": "^0.1.0",
```

2022-07-31 21:39 UTC, gregberge requested changes
Please remove the "version" upgrade.

2022-08-01 09:16 UTC, gregberge approved these changes

2022-08-01 09:17 UTC, merged